version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: barbearia_bd
    restart: unless-stopped
    networks:
      - barbearia
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: barbearia
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - barbearia_postgres-data:/var/lib/postgresql/data

volumes:
  barbearia_postgres-data:

networks:
  barbearia:
    driver: bridge